### ISSUE TITLE
question about the computation in functions compute_1F1 _Nd

### ISSUE THREAD

**Issue by weigert** [SebastianRiedel/bingham#10]
Hi. I have a question about the implementation of the computation of the hypergeometric function of matrix argument in non-canonical form. This relates to the file `bingham_constants.c` [here](https://github.com/SebastianRiedel/bingham/blob/master/c/bingham_constants.c).

I was studying this library to see how the normalization constant of the bingham distribution is computed and am confused about the rescaling in case of negative eigenvalues.

I made the following observations:

- Your largest Eigenvalue is apparently given by `z1`, indicated by the fact that you state the distribution is uniform if it is below epsilon. So you just return the area of the hypersphere.
- If you find that your smallest Eigenvalue is below epsilon, you solve the normalization constant as a lower-dimensional problem.
- If you find that your largest Eigenvalue is negative, you do some weird stuff.
- Otherwise, you say that z1 ... zd are in canonical order and just evaluate.

The weird stuff:

- If the normalization constant if `N(Z) = |S^{d-1}| * 1F1(1/2, d/2, Z)` then it is known that `N(Z + c*I) = exp(c) * N(Z)`.
- You rescale the result of the shifted distribution as if you had shifted by z1, but you actually shifted the first eigenvalue by `2*z1` and the other eigenvalues by z1.

Also: Why do you swap the order of the last to eigenvalues for d = 3? 

My thoughts: 
- If z1 < 0 and they are in non-absolute value order, i.e. z3 < z2 < z1 < 0, then flipping the sign of z1 and adding it once to each guy doesn't change the order of z2 and z3 and potentially still leaves the other two eigenvalues negative, which conflicts with the comment on the canonical form computation.
- If z1 < 0 and the are in absolute value order, i.e. z1 < z2 < z3 < 0, then adding z1 to each would guarantee they are all positive but then the order is wrong, and flipping the sign of z1 would work but then you have to scale by `exp(2*z1)` and the other values indeed swap order but you have to add `-2*z1` to them. So this is where I'm confused.

Additionally, I was wondering if there was a reference for your implementation of the canonical form computation. It looks to me like it could be related to a laplace approximation but there is no reference anywhere. I ran some tests and it appears to be correct, but this would still be helpful.

Example reference function I am talking about:
        
        static double compute_1F1_3d(int dim, double z1, double z2, double z3, int iter)
        {
          if (fabs(z1) < EPSILON)  // uniform
            return surface_area_sphere(dim);
        
          if (fabs(z3) < EPSILON)  // z3 = 0
            return sqrt(M_PI)*compute_1F1_2d(dim, z1, z2, iter);
        
          if (z1 < 0) //WHAT IS GOING ON HERE????
            return exp(z1)*compute_1F1_3d(dim, -z1, z3-z1, z2-z1, iter);
        
          //alternative:
          // return exp(-2*z1)*compute_1F1_3d(dim, -z1, z3-2*z1, z2-2*z1, iter);

          return compute_1F1_3d_canon(.5, .5*(dim+1), z1, z2, z3, iter);
        }

**Comment by jglov3id** [comment]
Hi Nick,

The formulas are derived in section 2.2.1 of my thesis:
https://dspace.mit.edu/handle/1721.1/89992

Best,
Jared

**Comment by weigert** [comment]
Hi Jared,

I actually just found this and am reading it now. Thanks a lot!
